export const kosts = [
      {
        name: "Kost Ibu Made",
        bed: "Double Bed",
        parking: true,
        size: "Family",
        review: 258,
        rating: 5,
        price: "1500k",
        day: "per month",
        region: "Denpasar Selatan",
        dateAdded: "2023-05-01",
      },
      {
        name: "Kost Pak Agung",
        bed: "Single Bed",
        parking: false,
        size: "Single",
        review: 50,
        rating: 3,
        price: "500k",
        day: "per 6 month",
        region: "Denpasar Selatan",
        dateAdded: "2023-04-15",
      },
      {
        name: "Kost Bu Yuni",
        bed: "Single Bed",
        parking: true,
        size: "Family",
        review: 28,
        rating: 4,
        price: "700k",
        day: "per month",
        region: "Denpasar Timur",
        dateAdded: "2023-03-20",
      },
      {
        name: "Kost Bu Winda",
        bed: "Single Bed",
        parking: true,
        size: "Family",
        review: 150,
        rating: 5,
        price: "850k",
        day: "per year",
        region: "Denpasar Barat",
        dateAdded: "2023-02-10",
      },
      {
        name: "Kost Bu Rini",
        bed: "Double Bed",
        parking: true,
        size: "Single",
        review: 75,
        rating: 4,
        price: "1200k",
        day: "per month",
        region: "Denpasar Selatan",
        dateAdded: "2023-01-25",
      },
      {
        name: "Kost Pak Budi",
        bed: "Single Bed",
        parking: false,
        size: "Single",
        review: 30,
        rating: 3,
        price: "600k",
        day: "per 6 month",
        region: "Denpasar Selatan",
        dateAdded: "2022-12-10",
      },
      {
        name: "Kost Ibu Sari",
        bed: "Double Bed",
        parking: true,
        size: "Family",
        review: 200,
        rating: 5,
        price: "1600k",
        day: "per month",
        region: "Denpasar Selatan",
        dateAdded: "2022-11-05",
      },
    ];
    